language: python
python:
  - "3.7"

# de-activate submodules for now (while Trajectron is private)
git:
  submodules: false
before_install:
  - echo -e "machine github.com\n  login simon-schaefer\n  password $CI_USER_PASSWORD" >~/.netrc
  - git submodule update --init --recursive

# installation add-ons (for travis ci linux-based system)
addons:
  apt:
    packages:
    - pkgconf
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libmetis-dev

# command to install dependencies
install:
  - PROJECT_PATH="/home/travis/build/simon-schaefer/mantrap"

  - echo "Python requirement installation"
  - pip install -r ops/requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$PROJECT_PATH
  - pip install -r third_party/sgan/requirements.txt
  - pip install -r third_party/GenTrajectron/requirements.txt

  - echo "IPOPT installation"
  - cd third_party/Ipopt || return
  - mkdir build
  - ./coinbrew fetch Ipopt --no-prompt
  - ./coinbrew build Ipopt --prefix=/home/travis/build/simon-schaefer/mantrap/third_party/Ipopt/build --test --no-prompt
  - ./coinbrew install Ipopt  --no-prompt

  - cd /home/travis/build/simon-schaefer/mantrap/third_party
  - git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git
  - cd ThirdParty-Mumps
  - ./get.Mumps
  - ./configure
  - make
  - sudo make install

  - export PKG_CONFIG_PATH="/home/travis/build/simon-schaefer/mantrap/third_party/Ipopt/build/Ipopt/master"
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/travis/build/simon-schaefer/mantrap/third_party/Ipopt/build/ThirdParty/Mumps/2.0"
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/travis/build/simon-schaefer/mantrap/third_party/Ipopt/build/ThirdParty/Metis/2.0"
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/travis/build/simon-schaefer/mantrap/third_party/ThirdParty-Mumps/"

  - echo "CYIPOPT installation"
  - cd /home/travis/build/simon-schaefer/mantrap/third_party
  - wget https://files.pythonhosted.org/packages/05/57/a7c5a86a8f899c5c109f30b8cdb278b64c43bd2ea04172cbfed721a98fac/ipopt-0.1.9.tar.gz
  - tar -xzvf ipopt-0.1.9.tar.gz
  - mv ipopt-0.1.9 cyipopt
  - cd cyipopt || return
  - python setup.py install

  - export LD_LIBRARY_PATH="/home/travis/build/simon-schaefer/mantrap/third_party/Ipopt/build/lib"
  - cd /home/travis/build/simon-schaefer/mantrap

  - cd third_party
  - sudo apt-get install unzip
  - wget $RESSOURCES_URL -O ressoures.zip
  - unzip ressoures.zip
  - mv mantrap/trajectron_models .  # trajectron model
  - mv mantrap/reachability .  # reachability values
  - cd sgan  # sgan models
  - bash scripts/download_model.sh
  - cd /home/travis/build/simon-schaefer/mantrap

# command to run tests. 
script:
  - coverage run -m pytest test/

# Push the results back to codecov
after_success:
  - codecov
