coverage:
  range: 50..85 # coverage lower than 50 is red, higher than 85 green, between color code

  status:
    project:
      enabled: yes
      target: auto
      threshold: 5%

    patch: off
    changes: off

  ignore:
    - "mantrap_evaluation"
    - "mantrap/visualization"
    - "third_party"